### ISSUE TITLE
Errore in user_members?

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#25]
Questa serie di interrogazioni mi da errore:

``` ruby
g = RubyProvisioningApi::Group.find "fake"
g.user_members

RubyProvisioningApi::EntityDoesNotExist: Entity does not exist
    from /home/davide/sites/ruby_provisioning_api/lib/ruby_provisioning_api/entity.rb:26:in `check_response'
    from /home/davide/sites/ruby_provisioning_api/lib/ruby_provisioning_api/user.rb:71:in `find'
    from /home/davide/sites/ruby_provisioning_api/lib/ruby_provisioning_api/member.rb:98:in `block in members'
    from /home/davide/sites/ruby_provisioning_api/lib/ruby_provisioning_api/member.rb:98:in `map'
    from /home/davide/sites/ruby_provisioning_api/lib/ruby_provisioning_api/member.rb:98:in `members'
    from /home/davide/sites/ruby_provisioning_api/lib/ruby_provisioning_api/member.rb:15:in `user_members'
    from (irb):27
    from /home/davide/.rvm/rubies/ruby-1.9.2-p320/bin/irb:16:in `<main>'
```

**Comment by dbraga** [comment]
Prendo in carico

**Comment by dbraga** [comment]
Collegato alla issue #21

In pratica avevo aggiunto dei membri che non esistevano (ne come user, ne come gruppi) e nella find falliva.
questo e' un wontfix perche' se mettiamo il controllo "all'aggiunta" di un membro/owner il bug non e' ripresentabile

**Comment by davide-targa** [comment]
ok, grazie
